### ISSUE TITLE
base/crc32.h is missing

### ISSUE THREAD

**Issue by K0stIa** [dmlc/wormhole#15]
make linear fails now

make[1]: Entering directory `/mnt/home.dokt/antonkos/code/dmlc/wormhole/learn/linear'
make[1]: *** No rule to make target `../base/crc32.h', needed by `build/linear.o'.  Stop.
make[1]: Leaving directory `/mnt/home.dokt/antonkos/code/dmlc/wormhole/learn/linear'
make: *** [learn/linear/build/linear.dmlc] Error 2

**Comment by mli** [comment]
crc32.h is replaced by citiy.h and has been deleted. please do a `make clean` (you may do a `git pull` first)
