### ISSUE TITLE
Extend wormhole Async to include dropouts

### ISSUE THREAD

**Issue by mpearmain** [dmlc/wormhole#16]
Have you thought about adding dropouts as an enhancement?
Similar to the below
https://github.com/bingzhengwei/ftrl_proximal_lr

**Comment by mli** [comment]
does it help? i implemented dropout in difacto (factorization machine). it only helps on some datasets. i'm wonder if it's necessary for the much simpler linear method

**Comment by mpearmain** [comment]
On the Avazu Kaggle competition i benefited from dropouts with multiple passes of the data.

**Comment by mli** [comment]
thanks for the explanation. can i ask you to do me a favor to test the dropout if it's implemented?

**Comment by mpearmain** [comment]
No problem at all,
I have been doing some more testing today on private data to verify the
results are scalable
