### ISSUE TITLE
wormhole xgboost doesn't build with HDFS

### ISSUE THREAD

**Issue by antonymayi** [dmlc/wormhole#19]
Despite building wormhole with USE_HDFS=1 the xgboost tool is not built that way:

    terminate called after throwing an instance of 'std::runtime_error'
    what(): xgboost is compiled in local mode
    to use hdfs, s3 or distributed version, compile with make dmlc=1
    Aborted

**Comment by tqchen** [comment]
You do need to make xgboost under this folder. Copy the ```config.mk``` to root folder, modify it to enabled HDFS /S3 , and type ```make xgboost```

**Comment by mli** [comment]
it can be done by `make xgboost USE_HDFS=1` if `HADOOP_HOME` and `JAVE_HOME` have been set properly
