### ISSUE TITLE
ubuntu14.04不能编译

### ISSUE THREAD

**Issue by selay01** [dmlc/wormhole#25]
rm -rf cityhash-1.1.1.tar.gz cityhash-1.1.1
wget https://raw.githubusercontent.com/mli/deps/master/build/cityhash-1.1.1.tar.gz && tar -zxf cityhash-1.1.1.tar.gz
--2015-08-26 04:49:28--  https://raw.githubusercontent.com/mli/deps/master/build/cityhash-1.1.1.tar.gz
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 103.245.222.133
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|103.245.222.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 376456 (368K) [application/octet-stream]
正在保存至: “cityhash-1.1.1.tar.gz”

100%[======================================>] 376,456      106KB/s   用时 3.5s 

2015-08-26 04:49:34 (106 KB/s) - 已保存 “cityhash-1.1.1.tar.gz” [376456/376456])

cd cityhash-1.1.1 && ./configure -prefix=/home/selay/wormhole/deps --enable-sse4.2 && make CXXFLAGS="-g -O3 -msse4.2" && make install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 805306365
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether byte ordering is bigendian... no
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for inline... inline
checking for size_t... yes
checking for ssize_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking if the compiler supports __builtin_expect... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
## config.status: executing libtool commands

CityHash Version 1.1.1

Prefix: '/home/selay/wormhole/deps'.
Compiler: 'g++ -g -O2'

Now type 'make [<target>]'
  where the optional <target> is:
    all                - build everything
    check              - build and run tests
    install            - install everything

---

make[1]: 正在进入目录 `/home/selay/wormhole/cityhash-1.1.1'
make  all-recursive
make[2]: 正在进入目录`/home/selay/wormhole/cityhash-1.1.1'
Making all in src
make[3]: 正在进入目录 `/home/selay/wormhole/cityhash-1.1.1/src'
/bin/bash ../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..     -g -O3 -msse4.2 -MT city.lo -MD -MP -MF .deps/city.Tpo -c -o city.lo city.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -g -O3 -msse4.2 -MT city.lo -MD -MP -MF .deps/city.Tpo -c city.cc  -fPIC -DPIC -o .libs/city.o
city.cc: In function 'void CityHashCrc256Long(const char*, size_t, uint32, uint64*)':
city.cc:535:31: error: '_mm_crc32_u64' was not declared in this scope
     z = _mm_crc32_u64(z, b + g);                \
                               ^
city.cc:542:5: note: in expansion of macro 'CHUNK'
     CHUNK(0); PERMUTE3(a, h, c);
     ^
city.cc:535:31: error: '_mm_crc32_u64' was not declared in this scope
     z = _mm_crc32_u64(z, b + g);                \
                               ^
city.cc:551:5: note: in expansion of macro 'CHUNK'
     CHUNK(29);
     ^
city.cc:535:31: error: '_mm_crc32_u64' was not declared in this scope
     z = _mm_crc32_u64(z, b + g);                \
                               ^
city.cc:561:5: note: in expansion of macro 'CHUNK'
     CHUNK(33);
     ^
make[3]: *** [city.lo] 错误 1
make[3]:正在离开目录`/home/selay/wormhole/cityhash-1.1.1/src'
make[2]: **\* [all-recursive] 错误 1
make[2]:正在离开目录 `/home/selay/wormhole/cityhash-1.1.1'
make[1]: *** [all] 错误 2
make[1]:正在离开目录`/home/selay/wormhole/cityhash-1.1.1'
make: **\* [/home/selay/wormhole/deps/include/city.h] 错误 2

**Comment by mli** [comment]
it looks like your cpu doesn't support sse, you can disable it by removing `--enable-sse4.2` at https://github.com/dmlc/wormhole/blob/master/make/deps.mk#L80

**Comment by selay01** [comment]
看来应该是cpu不支持sse！但是要同时去掉 --enable-sse4.2 和  -msse4.2 at
https://github.com/dmlc/wormhole/blob/master/make/deps.mk#L80 才行。

**Comment by selay01** [comment]
tracker/dmlc_local.py -n 2 -s 1 bin/linear.dmlc learn/linear/guide/demo.conf 后：

2015-09-07 01:05:26,838 INFO start listen on 127.0.1.1:9091
Connected 1 servers and 2 workers
Training: iter = 0
  sec   ttl #ex   inc #ex    |w|_0       logloss  accuracy     AUC
    1  6.51e+03  6.51e+03          117  0.544605  0.813140  0.875864
Validating: iter = 0
  sec   ttl #ex   inc #ex    |w|_0       logloss  accuracy     AUC
    2  8.12e+03  1.61e+03          117  0.305350  0.924250  0.962958
Training: iter = 1
  sec   ttl #ex   inc #ex    |w|_0       logloss  accuracy     AUC
    3  1.46e+04  6.51e+03          117  0.257834  0.913870  0.973025
Validating: iter = 1
  sec   ttl #ex   inc #ex    |w|_0       logloss  accuracy     AUC
    4  1.62e+04  1.61e+03          117  0.218789  0.942290  0.985475
Training: iter = 2
  sec   ttl #ex   inc #ex    |w|_0       logloss  accuracy     AUC
    5  2.28e+04  6.51e+03          117  0.202892  0.932146  0.988814
Validating: iter = 2
  sec   ttl #ex   inc #ex    |w|_0       logloss  accuracy     AUC
    6  2.44e+04  1.61e+03          117  0.180686  0.955943  0.990899
Hit max number of data passes 3
Saving the final model
Training is finished!

看来是make成功了！！谢谢！！！
