### ISSUE TITLE
Online Prediction

### ISSUE THREAD

**Issue by mpearmain** [dmlc/wormhole#26]
FEATURE REQUEST:

Is it possible to link wormhole as a library and call the predict function in-process for realtime predictions off a set of (pred_model*) prediction files?

**Comment by mli** [comment]
do you need it for a online service? it's quite easy to have an easy solution, basically just a simple program loads the model and does the prediction. a more general solution using the server/worker framework might be not so straightforward.

**Comment by mpearmain** [comment]
Hi Mu,

Yes the intention was for an online service with a server / worker
framework, as i suspect there maybe reasonably high traffic loads

**Comment by mli** [comment]
hi Michael,

it depends whether or not the whole model can be loaded into a single machine. if yes, then it should be easy. otherwise we need to some engineering works. there is a good reference: http://research.google.com/pubs/pub40801.html

**Comment by mpearmain** [comment]
Well that's good news, as the answer is yes. I can load into a single machine
