### ISSUE TITLE
*** Check failure stack trace: *** 已放弃 (核心已转储)

### ISSUE THREAD

**Issue by selay01** [dmlc/wormhole#27]
按照http://wormhole.readthedocs.org/en/latest/tutorial/criteo_kaggle.html，
运行wormhole/bin/text2crb.dmlc train.txt data/train criteo 300时，出现
**\* Check failure stack trace: **\* 已放弃 (核心已转储)

**Comment by mli** [comment]
text2crb.dmlc is replaced by convert.dmlc, i don't know why the document hasn't updated

#23

**Comment by selay01** [comment]
OK.i will try it agin,think you!

**Comment by selay01** [comment]
使用
wormhole/bin/convert.dmlc -data_in train.txt -format_in criteo -data_out data/train -format_out libsvm -part_size 300

依然是：
*** Check failure stack trace: ***
已放弃 (核心已转储)
