### ISSUE TITLE
can not get the correct predict result

### ISSUE THREAD

**Issue by catmonkeylee** [dmlc/wormhole#34]
I has used xgboost (single machine version) before， recently I used distributed version on hadoop to train model. And I get the trained model from hadoop, then used the python wrappered xgboost  to predict, but the predict result is terrible. But if I use the xgboost.dmlc tool to predict, the result is correct. I'm reading the source code, may be the python wrappered xgboost not load model correct？

**Comment by tqchen** [comment]
As far as I know, the model should be compatible between different versions. Please make sure you compile the latest xgboost. If you think there is problem. Please check the consistency of the simple model and see if there is a difference.

You mentioned you used single node version. You might want to make sure that your dataset generation is same as libsvm format used in distributed version. Specifically,  pass sparse matrix as in libsvm to xgboost

**Comment by catmonkeylee** [comment]
It's my fault ,  I read the source code and found ,   when I use "sklearn.datasets.load_svmlight_files" function to load data from file ,  I set the zero_based=False,  and the sparse matrix retured was error,   and I used this error matrix data to call predict.   So everything down.  Thanks again.
