### ISSUE TITLE
troubleshooting yarn job

### ISSUE THREAD

**Issue by ygan1129** [dmlc/wormhole#45]
I built wormhole for Yarn, HDFS, and S3, and the make succeeded, but when I try to run the example xgboost command the job reads as FINISHED but FAILED in the Resource Manager and no final model is output to hdfs.  What's a good way to troubleshoot this?  There's nothing in the stderr, stdout, or syslog logs, and I'm struggling to figure out what the error is.

**Comment by tqchen** [comment]
You want to check worker error logs from each of the worker

**Comment by ygan1129** [comment]
I figured out I was having the same issue as some of the others with xgboost compiling in local mode instead of yarn mode, and now xgboost works using the fix provided, but I haven't been able to get the asynchronous SGD to work with logistic regression.  Running the demo_yarn.sh in learn/linear with build/linear.dmlc instead of build/async_sgd gives me the following error: 

F1121 00:07:19.113471 13722 io.cc:38] Please compile with DMLC_USE_HDFS=1 to use hdfs
*** Check failure stack trace: ***
    @           0x4ec6aa  google::LogMessage::Fail()
    @           0x4ee572  google::LogMessage::SendToLog()
    @           0x4ec28f  google::LogMessage::Flush()
    @           0x4eee8e  google::LogMessageFatal::~LogMessageFatal()
    @           0x43e6c9  dmlc::io::FileSystem::GetInstance()
    @           0x418a75  dmlc::MatchFile()
    @           0x41926e  dmlc::WorkloadPool::Match()
    @           0x439d64  dmlc::solver::DataParScheduler::StartDispatch()
    @           0x43a333  dmlc::solver::MinibatchScheduler::Run()
    @           0x46db78  ps::Manager::Run()
    @           0x4658d9  ps::Postoffice::Run()
    @           0x407911  main
    @     0x7f78a53bdaf5  __libc_start_main
    @           0x4098f1  (unknown)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hadoop/wormhole/learn/linear/dmlc-core/tracker/tracker.py", line 345, in <lambda>
    self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/hadoop/wormhole/learn/linear/dmlc-core/yarn/run_hdfs_prog.py ../build/linear.dmlc demo_hdfs.conf ' returned non-zero exit status 250

Did something go wrong in the make?  I managed to get xgboost to work with YARN and HDFS, but it does not seem to be working with the linear method.

**Comment by ygan1129** [comment]
I figured out that the issue was with not building with the DMLC_USE_HDFS=1 flag when I was using the "make linear" command, but now I get the following error in my containers immediately after the application is submitted in YARN:
F1124 18:37:47.294451 20578 manager.cc:55] Timeout (10 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @           0x4ec6aa  google::LogMessage::Fail()
    @           0x4ee572  google::LogMessage::SendToLog()
    @           0x4ec28f  google::LogMessage::Flush()
    @           0x4eee8e  google::LogMessageFatal::~LogMessageFatal()
    @           0x46dbe2  ps::Manager::Run()
    @           0x4658d9  ps::Postoffice::Run()
    @           0x407911  main
    @     0x7f0216c02af5  __libc_start_main
    @           0x4098f1  (unknown)

**Comment by linhuifj** [comment]
this may because 10second is not enough for the programs to start on your yarn cluster machines. modify the code and change it with 30second or larger.

**Comment by formath** [comment]
@ygan1129 Have you fixed this problem?
F0701 16:51:13.041448  7519 manager.cc:55] Timeout (10 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @           0x50078f  google::LogMessage::SendToLog()
    @           0x4fd69c  google::LogMessage::Flush()
    @           0x4fd96d  google::LogMessageFatal::~LogMessageFatal()
    @           0x477562  ps::Manager::Run()
    @           0x47df15  ps::Postoffice::Run()
    @           0x425b41  main
    @     0x7ffc9742ad5d  __libc_start_main
    @           0x411eb5  (unknown)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/meituan/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/meituan/python/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sankuai/liujinpeng02/github/wormhole/repo/dmlc-core/tracker/dmlc_tracker/tracker.py", line 363, in <lambda>
    target=(lambda: subprocess.check_call(self.cmd, env=env, shell=True)), args=())
  File "/opt/meituan/python/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by CNevd** [comment]
@formath just change the sync_timeout [here](https://github.com/CNevd/Difacto_DMLC/blob/master/ps-lite/src/system/manager.cc#L11)
