### ISSUE TITLE
xgboost on yarn seems getting stuck

### ISSUE THREAD

**Issue by robbine** [dmlc/wormhole#48]
I'm running mushroom example on yarn like this, 
tracker/dmlc_yarn.py  -n 4 --vcores 2 \
      bin/xgboost.dmlc \
      learn/xgboost/mushroom.hadoop.conf nthread=2 \
         data=hdfs://${hdfs_path}/expdata/agaricus.txt.train \
            eval[testhdfs://${hdfs_path}/expdata/agaricus.txt.test \
              model_out=s://${hdfs_path}/mushroom.final.model

These messages are printed on screen:
2015-11-26 14:26:25,491 INFO @tracker All of 4 nodes getting started
2015-11-26 14:26:29,634 INFO [0]	train-error:0.014433
[0]	train-error:0.014433
2015-11-26 14:26:29,914 INFO [1]	train-error:0.001228
[1]	train-error:0.001228

and it has not finished after 20 minutes
Have anyone seen this before ?

**Comment by tqchen** [comment]
The original version indeed only runs for two iterations, can you check your logs to see if anything wrong happens?

**Comment by robbine** [comment]
ok, yes. i made a mistake.
thank you

**Comment by robbine** [comment]
hi Tianqi,
Is there a way to check job progress like a web UI ?
Or else I have no idea what's going on.
I see that you provide both reg:linear and reg:logistic, For ranking
problem, which would you recommend?
Thanks a lot !

2015-11-26 14:51 GMT+08:00 Tianqi Chen <notifications@github.com>:

**Comment by tqchen** [comment]
You can get into each of the workers, and check the stdout stderr logs of the worker

**Comment by robbine** [comment]
thanks！
If I have a training path containing many partitions. How can I use all of
them ?
For example the folder name is libsvmTrain, I tried 3 different ways like
data=hdfs:///libsvmTrain/
data=hdfs:///libsvmTrain/*
data=hdfs:///libsvmTrain
None of them works.

**Comment by tqchen** [comment]
data=hdfs:///libsvmTrain/ should work, except that you need to make sure it is absolute path to the folder and the folder do not contain additional files

**Comment by robbine** [comment]
I tried . An IOException is thrown.
   1
   2
   3 Container: container_1448593333704_15438_01_000003 on
hadoop149.photo.163.org_54444
   4
=====================================================================================
   5 LogType: stderr
   6 LogLength: 719
   7 Log Contents:
   8 connect to ip: [10.160.128.51]
   9 start hadoop149.photo.163.org:19
  10 readDirect: FSDataInputStream#read error:
  11 java.io.IOException: Filesystem closed
  12     at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:730)
  13     at
org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:779)
  14     at
org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:847)
  15     at
org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:143)
  16 [13:46:35] include/dmlc/logging.h:208: [13:46:35]
src/io/hdfs_filesys.cc:44: HDFSStream.hdfsRead Error:Unknown error 255
  17 terminate called after throwing an instance of 'dmlc::Error'
  18   what():  [13:46:35] src/io/hdfs_filesys.cc:44: HDFSStream.hdfsRead
Error:Unknown error 255
  19
  20 LogType: stdout
  21 LogLength: 0
  22 Log Contents:


2015-11-28 2:09 GMT+08:00 Tianqi Chen <notifications@github.com>:

**Comment by brickerino** [comment]
Just got the same error with 'Filesystem is closed'. It was because i manually killed application while it was working normal. I don't know, may be i iterrupted reading process and i got such message.
So, if somebody get this error, just restart your job and wait longer, than the last time.
