### ISSUE TITLE
falied on make

### ISSUE THREAD

**Issue by andyyuan78** [dmlc/wormhole#5]
ubgpu@ubgpu:~/github/wormhole$ cp  make/config.mk  ./
ubgpu@ubgpu:~/github/wormhole$ make
cd dmlc-core; make libdmlc.a config=/home/ubgpu/github/wormhole/config.mk; cd /home/ubgpu/github/wormhole
make[1]: Entering directory `/home/ubgpu/github/wormhole/dmlc-core'
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=1 -I/include -I/include -DDMLC_USE_S3=1 -o io.o src/io.cc
In file included from src/io.cc:17:0:
src/io/hdfs_filesys.h:10:18: fatal error: hdfs.h: No such file or directory
 #include <hdfs.h>
                  ^
compilation terminated.
make[1]: *** [io.o] Error 1
make[1]: Leaving directory `/home/ubgpu/github/wormhole/dmlc-core'
cd repo/xgboost; make dmlc=/home/ubgpu/github/wormhole/dmlc-core config=/home/ubgpu/github/wormhole/config.mk
make[1]: Entering directory `/home/ubgpu/github/wormhole/repo/xgboost'
make[1]: *** No rule to make target `/home/ubgpu/github/wormhole/dmlc-core/libdmlc.a', needed by `xgboost'.  Stop.
make[1]: Leaving directory `/home/ubgpu/github/wormhole/repo/xgboost'
make: *** [repo/xgboost/xgboost] Error 2
ubgpu@ubgpu:~/github/wormhole$ 

even I build xgboost like

ubgpu@ubgpu:~/github/wormhole/repo/xgboost$ ./build.sh 
g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC         -fPIC -shared -o wrapper/libxgboostwrapper.so wrapper/xgboost_wrapper.cpp updater.o gbm.o io.o subtree/rabit/lib/librabit.a dmlc_simple.o -pthread -lm  
Successfully build multi-thread xgboost
ubgpu@ubgpu:~/github/wormhole/repo/xgboost$ cd -
/home/ubgpu/github/wormhole

 I still got this error

**Comment by tqchen** [comment]
As the error indicates, it can not find hdfs. You can modify config.mk to solve this problem(either config HDFS correctly or remove HDFS dependency)

**Comment by andyyuan78** [comment]
cool. it works!
