### ISSUE TITLE
wormhole no longer makes

### ISSUE THREAD

**Issue by ygan1129** [dmlc/wormhole#57]
I had no issue running make for wormhole in November, but I recently tried again after cloning the latest git and received the following error and the make did not succeed:

g++ -O3 -ggdb -Wall -std=c++11 -I./ -I../ -I../../repo/ps-lite/src -I../../repo/dmlc-core/include -I../../repo/dmlc-core/src -I/home/hadoop/wormhole/deps/include -fopenmp -fPIC -DDMLC_USE_HDFS=1 -I/home/hadoop/.versions/2.4.0-amzn-5/include -I/usr/java/latest/include -DDMLC_USE_S3=1 -DDMLC_USE_GLOG=1 -DDMLC_USE_AZURE=0   -MM -MT build/linear.o linear.cc >build/linear.d
g++ -O3 -ggdb -Wall -std=c++11 -I./ -I../ -I../../repo/ps-lite/src -I../../repo/dmlc-core/include -I../../repo/dmlc-core/src -I/home/hadoop/wormhole/deps/include -fopenmp -fPIC -DDMLC_USE_HDFS=1 -I/home/hadoop/.versions/2.4.0-amzn-5/include -I/usr/java/latest/include -DDMLC_USE_S3=1 -DDMLC_USE_GLOG=1 -DDMLC_USE_AZURE=0   -c linear.cc -o build/linear.o
In file included from ../base/workload_pool.h:5:0,
                 from ../solver/data_parallel.h:8,
                 from ../solver/iter_solver.h:5,
                 from ../solver/minibatch_solver.h:5,
                 from async_sgd.h:5,
                 from linear.cc:1:
../base/match_file.h: In function ‘void dmlc::MatchFile(const string&, std::vector<std::basic_string<char> >*)’:
../base/match_file.h:22:58: error: no matching function for call to ‘dmlc::io::FileSystem::GetInstance(std::string&)’
       dmlc::io::FileSystem::GetInstance(path_uri.protocol);
                                                          ^
../base/match_file.h:22:58: note: candidate is:
In file included from ../base/match_file.h:2:0,
                 from ../base/workload_pool.h:5,
                 from ../solver/data_parallel.h:8,
                 from ../solver/iter_solver.h:5,
                 from ../solver/minibatch_solver.h:5,
                 from async_sgd.h:5,
                 from linear.cc:1:
../../repo/dmlc-core/src/io/filesys.h:84:22: note: static dmlc::io::FileSystem* dmlc::io::FileSystem::GetInstance(const dmlc::io::URI&)
   static FileSystem *GetInstance(const URI &path);
                      ^
../../repo/dmlc-core/src/io/filesys.h:84:22: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const dmlc::io::URI&’
make[1]: *** [build/linear.o] Error 1
make[1]: Leaving directory `/home/hadoop/wormhole/learn/linear'
make: *** [learn/linear/build/linear.dmlc] Error 2

The deps built successfully, it's only the wormhole packages that aren't building.

**Comment by zorksylar** [comment]
this can be fixed by merge #56 pull request.

**Comment by ygan1129** [comment]
Yeah I saw that and merged it in, but now ld isn't working with -lglog when I try to 'make linear':

g++ -O3 -ggdb -Wall -std=c++11 -I./ -I../ -I../../repo/ps-lite/src -I../../repo/dmlc-core/include -I../../repo/dmlc-core/src -I/home/hadoop/wormhole/deps/include -fopenmp -fPIC -DDMLC_USE_HDFS=1 -I/home/hadoop/.versions/2.4.0-amzn-5/include -I/usr/java/latest/include -DDMLC_USE_S3=1 -DDMLC_USE_GLOG=1 -DDMLC_USE_AZURE=0   build/config.pb.o build/linear.o ../../repo/dmlc-core/libdmlc.a ../../repo/ps-lite/build/libps.a -fopenmp -lrt -L/home/hadoop/lib/native -lhdfs -L/usr/java/latest/jre/lib/amd64/server -ljvm -Wl,-rpath=/usr/java/latest/jre/lib/amd64/server -lcurl -lssl -lcrypto -lglog /home/hadoop/wormhole/deps/lib/libprotobuf.a /home/hadoop/wormhole/deps/lib/libglog.a /home/hadoop/wormhole/deps/lib/libgflags.a /home/hadoop/wormhole/deps/lib/libzmq.a /home/hadoop/wormhole/deps/lib/libcityhash.a /home/hadoop/wormhole/deps/lib/liblz4.a  -o build/linear.dmlc
/usr/bin/ld: cannot find -lglog

I tried to fix this by adding -L/home/hadoop/wormhole/repo/dmlc-core/lib before -lglog, but then when I ran dmlc_yarn.py it could not find the libglog.so.0 library, so something must have gone wrong.  I never had this issue before when running in distributed mode.

**Comment by ygan1129** [comment]
Update: I removed the -lglog flag from the dmlc.mk file in dmlc-core and make linear succeeded, but now I'm encountering a new problem that I never encountered early in November:

2016-01-07 18:55:15,230 INFO start listen on 10.10.5.154:9091
16/01/07 18:55:17 INFO client.RMProxy: Connecting to ResourceManager at /10.10.5.154:9022
16/01/07 18:55:18 INFO metrics.MetricsSaver: MetricsConfigRecord disabledInCluster: false instanceEngineCycleSec: 60 clusterEngineCycleSec: 60 disableClusterEngine: false maxMemoryMb: 3072 maxInstanceCount: 500 
16/01/07 18:55:18 INFO metrics.MetricsSaver: Created MetricsSaver j-MO6RIUMOT7IJ:i-2e9161a7:Client:04467 period:60 /mnt/var/em/raw/i-2e9161a7_20160107_Client_04467_raw.bin
16/01/07 18:55:18 INFO dmlc.Client: jobname=DMLC[nworker=1,nsever=1]:linear.dmlc,username=hadoop
16/01/07 18:55:18 INFO dmlc.Client: Submitting application application_1452186855400_0001
16/01/07 18:55:19 INFO impl.YarnClientImpl: Submitted application application_1452186855400_0001
Connected 1 servers and 1 workers
Training: iter = 0
  sec   ttl #ex   inc #ex    |w|_0       logloss  accuracy     AUC
hdfsBuilderConnect(forceNewInstance=0, nn=, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
java.lang.IllegalArgumentException: Expected authority at index 7: hdfs://
        at java.net.URI.create(URI.java:859)
Caused by: java.net.URISyntaxException: Expected authority at index 7: hdfs://
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.failExpecting(URI.java:2835)
        at java.net.URI$Parser.parseHierarchical(URI.java:3083)
        at java.net.URI$Parser.parse(URI.java:3034)
        at java.net.URI.<init>(URI.java:595)
        at java.net.URI.create(URI.java:857)
F0107 18:55:29.778659  4498 hdfs_filesys.cc:95] Failed to load HDFS-configuration:
*** Check failure stack trace: ***
    @           0x4fbc7a  google::LogMessage::Fail()
    @           0x4fdb42  google::LogMessage::SendToLog()
    @           0x4fb85f  google::LogMessage::Flush()
    @           0x4fe45e  google::LogMessageFatal::~LogMessageFatal()
    @           0x449d58  dmlc::io::HDFSFileSystem::HDFSFileSystem()
    @           0x43f882  dmlc::io::FileSystem::GetInstance()
    @           0x419c25  dmlc::MatchFile()
    @           0x41a41e  dmlc::WorkloadPool::Match()
    @           0x43adf4  dmlc::solver::DataParScheduler::StartDispatch()
    @           0x43b3c3  dmlc::solver::MinibatchScheduler::Run()
    @           0x47d148  ps::Manager::Run()
    @           0x474ea9  ps::Postoffice::Run()
    @           0x408a81  main
    @     0x7fcf7c11daf5  __libc_start_main
    @           0x40aac1  (unknown)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hadoop/wormhole/repo/dmlc-core/tracker/tracker.py", line 345, in <lambda>
    self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/hadoop/wormhole/repo/dmlc-core/yarn/run_hdfs_prog.py /home/hadoop/wormhole/learn/linear/build/linear.dmlc /home/hadoop/wormhole/learn/linear/guide/demo_hdfs.conf -sync_timeout=1000 ' returned non-zero exit status 250

I'm guessing something was changed in ps-lite that is causing this to happen?  I've never had an issue with accessing hdfs before December.  Also, for future reference, I'm on AMI 2.4.0 (Amazon Linux) on AWS.

**Comment by ygan1129** [comment]
Further update: After some google-fu, I managed to get linear.dmlc to run by copying the fs.default.name field in core-site.xml and then modifying the demo_hdfs.conf file as:

train_data = "hdfs://${ip address went here}/agaricus.txt.train"
val_data = "hdfs://${ip address went here)/agaricus.txt.test"
max_data_pass = 3

I'm no expert on the intricacies of hdfs, so I'm not sure why wormhole is no longer picking up the hdfsHost?

**Comment by brickerino** [comment]
>I tried to fix this by adding -L/home/hadoop/wormhole/deps/lib before -lglog and it successfully built, but then when I ran dmlc_yarn.py it could not find the libglog.so.0 library, so something must have gone wrong. I never had this issue before when running in distributed mode.

You should or link library (libglog in this case) statically, by giving libglog.a file to the linker, or you should link dynamically, by giving -L/lalala/lib ans -lglog options, and in that case you have to transfer libglog.so dynamic library to the cluster with other your files, by giving option '--file libglog.so' to dmlc_yarn.py script.

In my case, i didn't manage to statically link libhdfs, because in my CDH distribution this library has position dependent code.
