### ISSUE TITLE
issue for the run_yarn.sh

### ISSUE THREAD

**Issue by panhongan** [dmlc/wormhole#67]
https://github.com/dmlc/wormhole/blob/master/learn/xgboost/run_yarn.sh

../../dmlc-core/tracker/dmlc_yarn.py used, but this file does not exist in dmlc-core.

does wormhole work well with dmlc-core ?

**Comment by tqchen** [comment]
check the newest guidehttps://xgboost.readthedocs.org/en/latest/tutorial/aws_yarn.html
