### ISSUE TITLE
CTR dataset on AWS -- mount timeout and mpirun connection timeout

### ISSUE THREAD

**Issue by chonglinsun** [dmlc/wormhole#7]
I ran the Criteo CTR  on AWS EC2, but I trapped in the mount step. 

When I ran command `sudo mount <master_ip>:/home/ubuntu /home/ubuntu`, I got a error: `mount.nfs: Connection timed out`.

And I also got a timeout error when I ran command `mpirun -hostfile hosts pwd` saying that `unable to connect from "ip-172-31-22-52" to "ip-172-31-22-51" (Connection timed out)`.

Would you please give some hints how to address this.

Thanks a lot.

**Comment by mli** [comment]
1. You need to replace master_ip by the actually internal ip of master machine, such as 172.31.22.52

2. Can you ping 172.31.22.51? Have you copied your pem file which is used to access the master machine into master's ~/.ssh/id_rsa?
